1:
	g++ -o 1_composition_example_main.exe 1_composition_example_main.cpp 1_composition_example_code.cpp
	./1_composition_example_main.exe


2:
	g++ -o 2_composition_another_example_main.exe 2_composition_another_example_main.cpp 2_composition_another_example_header.h
	./2_composition_another_example_main.exe

clean_all:
	rm *.exe
