1:
	g++ -o 1_composition_example_main.exe 1_composition_example_main.cpp 1_composition_example_code.cpp
	./1_composition_example_main.exe


2:
	g++ -o 2_composition_another_example_main.exe 2_composition_another_example_main.cpp 2_composition_another_example_header.h
	./2_composition_another_example_main.exe


3:
	g++ -o 3_composition_and_overloading_main.exe 3_composition_and_overloading_main.cpp 3_composition_and_overloading_code.cpp
	./3_composition_and_overloading_main.exe


4:
	g++ -o 4_hiding_main.exe 4_hiding_main.cpp 4_hiding_code.cpp
	./4_hiding_main.exe


5:
	g++ -o 5_multiple_inheritence_example_main.exe 5_multiple_inheritence_example_main.cpp
	./5_multiple_inheritence_example_main.exe


6:
	g++ -o 6_general_exercise_main.exe 6_general_exercise_main.cpp 6_general_exercise_codes.cpp
	./6_general_exercise_main.exe


clean_all:
	rm *.exe
