0:
	g++ -o 0_inclusion_polymophism_via_inheritence.exe 0_inclusion_polymophism_via_inheritence.cpp 
	./0_inclusion_polymophism_via_inheritence.exe


1:
	g++ -o 1_basic_overloading_example.exe 1_basic_overloading_example.cpp
	./1_basic_overloading_example.exe


clean_all:
	rm -v *.exe
