0:
	g++ -o 0_default_specific_and_copy_constructor_and_destructors.exe 0_default_specific_and_copy_constructor_and_destructors.cpp
	./0_default_specific_and_copy_constructor_and_destructors.exe


1:
	g++ -o 1_assignment_operator.exe 1_assignment_operator.cpp
	./1_assignment_operator.exe


2:
	g++ -o 2_overall_example.exe 2_overall_example.cpp
	./2_overall_example.exe


clean_all:
	rm *.exe
