0:
	g++ -o 0_default_specific_and_copy_constructor_and_destructors.exe 0_default_specific_and_copy_constructor_and_destructors.cpp
	./0_default_specific_and_copy_constructor_and_destructors.exe



clean_all:
	rm *.exe
