1:
	g++ -o 1_complex_numbers_example_main.exe 1_complex_numbers_example_main.cpp 1_complex_numbers_example_codes.cpp
	./1_complex_numbers_example_main.exe


2:
	g++ -o 2_operator_overload_main.exe 2_operator_overload_main.cpp 2_operator_overload_code.cpp
	./2_operator_overload_main.exe

clean_all:
	rm *.exe
