0_compile:
	gcc -o example_0.exe example_0.c

0_run:
	./example_0.exe

1_compile:
	gcc -o example_1.exe example_1.c

1_run:
	./example_1.exe

main_compile: main.c
	gcc -o main.exe main.c

main_run:
	./main.exe

clean_all:
	rm *.exe
