compile_chatgpt:
	gcc -o chatgpt_glthreads_example.exe chatgpt_glthreads_example.c -pthread

run_chatgpt:
	./chatgpt_glthreads_example.exe


compile_glthread:
	gcc -o glthread.exe glthread.c -pthread

run_glthread:
	./glthread.exe


compile_main:
	gcc -o main.exe main.c -pthread

run_main:
	./main.exe


clean_all:
	rm *.exe
